server:
  port: 8888
spring:
  application:
    name: itp-configserver

  profiles:
    active: git, vault

  cloud:
    config:
      server:
        # Vault config ----------------
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret
          profile-separator: /
         # Git config ------------------
        git:
          uri: ${GH_URI}
          username: ${GH_USER}
          password: ${GH_TOKEN}
          default-label: main
          search-paths: "/**"
          # Native config ---------------
        native:
          search-locations:
            - file:D:\ITP_SPRING_MICROSERVICE\itp-microservice\itp-config-repo\
            - file:D:\ITP_SPRING_MICROSERVICE\itp-microservice\itp-config-repo\{application}\